In [1]:
# from annotation_utils import *
import annotation_utils as utils
import numpy as np
import cv2

In [2]:
keypoints, anchors = utils.get_points_from_CAD()

normalized_keypoints = utils.normalize_and_orient_kpts(keypoints)
normalized_anchors = utils.normalize_and_orient_kpts(anchors)

In [3]:
#  calibration procedure is performed on warped image (tentative)
cv2.destroyAllWindows()
camera_params = [633.0902963939839, 638.754439101168,
                 629.0646296262861, 362.7401326185789]

anchor_ground_truth = np.array(
[(597, 349),
 (579, 325),
 (614, 324),
 (562, 350),
 (633, 349),
 (581, 380),
 (615, 379)])

img_with_marker_name = 'marker.jpg'
img_without_marker_name = 'no_marker.jpg'

img = cv2.imread(img_with_marker_name)

res = utils.detect_apriltag(img, camera_params)
img_warped, desired_corners,tform = utils.warp_img(img, res)

res_warp = utils.detect_apriltag(img_warped,camera_params)

anchor_on_image = utils.get_keypoints_on_warped_image(res_warp, normalized_anchors)
print("anchor difference in pix")
print(anchor_on_image-anchor_ground_truth)

# calculates corrected points from 1 shot
corrected_normalized_keypoints = utils.get_corrected_normalized_keypoints(res_warp,
                                        normalized_anchors,
                                        anchor_ground_truth,
                                        normalized_keypoints)

cv2.destroyAllWindows()

anchor difference in pix
[[-1.20193481  4.04702759]
 [-0.88820394  3.28625081]
 [-0.51566569  4.28625081]
 [-1.57447306  3.04702759]
 [-1.82939657  4.04702759]
 [-2.88820394  3.68848885]
 [-1.51566569  4.68848885]]
tform.params
[[ 0.99974498 -0.02258259  6.58793368]
 [ 0.02258259  0.99974498 -9.52870352]
 [ 0.          0.          1.        ]]
resulting transform to correct points
[[ 0.99418048  0.02680845 -4.55478108]
 [-0.01884702  0.9923276  10.08055214]]
inliers [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [4]:
normalized_keypoints - corrected_normalized_keypoints 

array([[ 0.00661054,  0.02794053],
       [ 0.0081001 ,  0.03276458],
       [-0.00088344,  0.02108112],
       [ 0.00571517,  0.04245128],
       [-0.00018844,  0.02688726],
       [ 0.00300284,  0.03722249],
       [-0.00619667,  0.02239062],
       [ 0.00052172,  0.04414872],
       [-0.0151436 ,  0.0204444 ],
       [-0.00586801,  0.0504842 ],
       [-0.03123926,  0.03289393],
       [-0.02641391,  0.04852125],
       [-0.03248225,  0.03303599],
       [-0.02753565,  0.04905596]])

In [5]:
def show_image_with_points(img,points, comment):
    for c in points:
        kc = int(c[0]), int(c[1])
        cv2.circle(img, kc, 3, (0,255, 255), -1)
    cv2.imshow(comment, img)
    cv2.waitKey(0)
    cv2.imwrite(comment+".jpg", img)

img_with_marker_name = 'marker.jpg'
img_without_marker_name = 'no_marker.jpg'


    # visualize the difference between corrected and original points
img = cv2.imread(img_with_marker_name)
points_on_image_corrected = utils.get_keypoints_on_image(img, corrected_normalized_keypoints,camera_params)
points_on_image = utils.get_keypoints_on_image(img,normalized_keypoints, camera_params)
                                                                                                                                                                                                                                                                                                            
img = cv2.imread(img_without_marker_name)
show_image_with_points(img,points_on_image, "no_correction")

img = cv2.imread(img_without_marker_name)
show_image_with_points(img,points_on_image_corrected, "correction points")

cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to tar

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to tar

In [10]:
cv2.destroyAllWindows()

In [7]:

img = cv2.imread(img_with_marker_name)
show_image_with_points(img,points_on_image, "kpts_on_marker")

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to target thread (0x5587a185c890)

QObject::moveToThread: Current thread (0x5587a185c890) is not the object's thread (0x5587a1992b50).
Cannot move to tar

In [8]:
import cv2
import numpy as np

source = np.float32([[0, 0], [100, 0], [100, 100], [0, 100]])
dest = np.float32([[0, 34], [-1000,15], [-1000, -1000], [16, -1000]])

points = np.float32([[[50, 50]]])

homography, _ = cv2.findHomography(source, dest)
print(homography)
transformed = cv2.perspectiveTransform(points, homography)

print(transformed)
# => [[[-500. -500.]]]

homography_inverse = np.linalg.inv(homography)
print(homography_inverse)
detransformed = cv2.perspectiveTransform(transformed, homography_inverse)
print(homography@homography_inverse)
print(detransformed)
# => [[[50. 50.]]]

[[-1.01871921e+01  1.57480315e-01  1.97208812e-13]
 [-1.87192118e-01 -1.01825197e+01  3.40000000e+01]
 [ 1.87192118e-04 -1.57480315e-04  1.00000000e+00]]
[[[-500.7417 -483.7669]]]
[[-9.81336242e-02 -1.51850869e-03  5.16292955e-02]
 [ 1.86637584e-03 -9.82303075e-02  3.33983046e+00]
 [ 1.86637584e-05 -1.51850869e-05  1.00051629e+00]]
[[ 1.00000000e+00  6.42290774e-19 -9.64612668e-17]
 [-2.18301106e-18  1.00000000e+00  9.32200205e-16]
 [ 0.00000000e+00  5.08219768e-21  1.00000000e+00]]
[[[50. 50.]]]


In [9]:
# reserved data
# from canny edge and hough circles
anchor_ground_truth = np.array(
    [[494.25,444.75,44.15],
  [636.75,362.25,42.5],
  [590.25,444.75,42.5],
  [537.75,360.75,47.45],
  [492.75,300.75,30.95],
  [450.75, 366.75,39.2],
  [582.75,299.25,30.95]])


anchor_ground_truth = np.array(
[(597, 349),
 (579, 325),
 (614, 324),
 (562, 350),
 (633, 349),
 (581, 380),
 (615, 379)])

img = cv2.imread('marker.jpg')