In [2]:
import numpy as np
import cv2
import os
from tqdm import tqdm

In [2]:
# PATH = 'LINEMOD/test_close/JPEGImages'
PATH = 'test_scene'

In [3]:
images_files = [x for x in os.listdir(PATH) if x != 'masks']
images_files.sort(key=lambda x: int(x.split('.')[0]))
len(images_files)

2419

In [12]:
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5),(2,2))
def mask_pic(img):
    mask = np.zeros(img.shape[:2], dtype=np.uint8)
    for i, k in enumerate(img):
        for j, _ in enumerate(k):
            if img[i,j,2] > 149 and img[i,j,1] < 115 and img[i,j,0] < 115:
                mask[i,j] = 255
    
    mask = cv2.erode(mask, kernel)
    mask = cv2.dilate(mask, kernel)
    
    contours = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)[0]
    
    for c in contours:
        if cv2.contourArea(c) < 400:
            cv2.fillPoly(mask, pts=[c], color=0)
    
    mask = cv2.dilate(mask, kernel, iterations=2)
    mask = cv2.erode(mask, kernel, iterations=3)
    mask = cv2.dilate(mask, kernel)
    
    return mask

In [11]:
indx = 0

In [13]:
file_name = images_files[indx]
img = cv2.imread(PATH+'/'+file_name)
img = cv2.resize(img, (960, 720), interpolation = cv2.INTER_AREA)

mask = mask_pic(img)
cv2.imshow('orig', img)
cv2.imshow('mask', mask)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.imwrite('test_scene/masks/'+file_name[:-3]+'jpg', mask)
indx +=1

QObject::moveToThread: Current thread (0x2f97470) is not the object's thread (0x3302010).
Cannot move to target thread (0x2f97470)

QObject::moveToThread: Current thread (0x2f97470) is not the object's thread (0x3302010).
Cannot move to target thread (0x2f97470)

QObject::moveToThread: Current thread (0x2f97470) is not the object's thread (0x3302010).
Cannot move to target thread (0x2f97470)

QObject::moveToThread: Current thread (0x2f97470) is not the object's thread (0x3302010).
Cannot move to target thread (0x2f97470)

QObject::moveToThread: Current thread (0x2f97470) is not the object's thread (0x3302010).
Cannot move to target thread (0x2f97470)

QObject::moveToThread: Current thread (0x2f97470) is not the object's thread (0x3302010).
Cannot move to target thread (0x2f97470)

QObject::moveToThread: Current thread (0x2f97470) is not the object's thread (0x3302010).
Cannot move to target thread (0x2f97470)

QObject::moveToThread: Current thread (0x2f97470) is not the object's thread

In [5]:
for file_name in tqdm(images_files):
    img = cv2.imread(PATH+'/'+file_name)
    mask = mask_pic(img)
    cv2.imwrite('test_scene/masks/'+file_name[:-3]+'jpg', mask)
#     cv2.imshow('orig', img)
#     cv2.imshow('mask', mask)
#     cv2.waitKey()
#     cv2.destroyAllWindows()

100%|█████████████████████████████████████| 2419/2419 [3:29:26<00:00,  5.19s/it]


In [5]:
masks_names = ['/'.join([x[0], 'masks', x[1]]) for x in images_files]

In [10]:
for file_name in tqdm(images_files):
    img = cv2.imread(PATH+'/'+file_name)
    
  
    resized = cv2.resize(img, (960, 720), interpolation = cv2.INTER_AREA)

# mask = mask_pic(img)
    cv2.imwrite(PATH+'/'+file_name,resized)
# cv2.imshow('mask', mask)
cv2.waitKey()
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x18ddfb0) is not the object's thread (0x16e6ac0).
Cannot move to target thread (0x18ddfb0)

QObject::moveToThread: Current thread (0x18ddfb0) is not the object's thread (0x16e6ac0).
Cannot move to target thread (0x18ddfb0)

QObject::moveToThread: Current thread (0x18ddfb0) is not the object's thread (0x16e6ac0).
Cannot move to target thread (0x18ddfb0)

QObject::moveToThread: Current thread (0x18ddfb0) is not the object's thread (0x16e6ac0).
Cannot move to target thread (0x18ddfb0)

QObject::moveToThread: Current thread (0x18ddfb0) is not the object's thread (0x16e6ac0).
Cannot move to target thread (0x18ddfb0)

QObject::moveToThread: Current thread (0x18ddfb0) is not the object's thread (0x16e6ac0).
Cannot move to target thread (0x18ddfb0)

QObject::moveToThread: Current thread (0x18ddfb0) is not the object's thread (0x16e6ac0).
Cannot move to target thread (0x18ddfb0)

QObject::moveToThread: Current thread (0x18ddfb0) is not the object's thread

In [ ]:

for file_name in tqdm(images_files):
    img = cv2.imread(PATH+'/'+file_name)

In [57]:
img = cv2.imread('/home/andrey/nvdiffrec/data/socket/imgs/1.jpg')
img *=255
cv2.imshow('a', img)
cv2.waitKey()
cv2.destroyWindow('a')

QObject::moveToThread: Current thread (0x256aed0) is not the object's thread (0x3498d80).
Cannot move to target thread (0x256aed0)

QObject::moveToThread: Current thread (0x256aed0) is not the object's thread (0x3498d80).
Cannot move to target thread (0x256aed0)

QObject::moveToThread: Current thread (0x256aed0) is not the object's thread (0x3498d80).
Cannot move to target thread (0x256aed0)

QObject::moveToThread: Current thread (0x256aed0) is not the object's thread (0x3498d80).
Cannot move to target thread (0x256aed0)

QObject::moveToThread: Current thread (0x256aed0) is not the object's thread (0x3498d80).
Cannot move to target thread (0x256aed0)

QObject::moveToThread: Current thread (0x256aed0) is not the object's thread (0x3498d80).
Cannot move to target thread (0x256aed0)

QObject::moveToThread: Current thread (0x256aed0) is not the object's thread (0x3498d80).
Cannot move to target thread (0x256aed0)

QObject::moveToThread: Current thread (0x256aed0) is not the object's thread

In [53]:
np.max(img)

3

In [3]:
tr = np.load('/home/andrey/nvdiffrec/data/test_close/transforms.npy')

In [5]:
tr[0]

array([[ 0.96469711,  0.26316243,  0.01024822, -0.19572743],
       [ 0.24624952, -0.88753311, -0.38941771, -0.0357335 ],
       [-0.09338448,  0.37819376, -0.92100424,  0.25767825],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [12]:
tr_new = tr.copy()
for i in tqdm(range(1,tr.shape[0])):
    tr_new[i] = tr_new[i-1] @ tr_new[i]

100%|███████████████████████████████████| 1190/1190 [00:00<00:00, 278310.57it/s]


In [9]:
tr_new[1:,1:3,:] *= -1

In [13]:
np.save('/home/andrey/nvdiffrec/data/test_close/transforms_inverse.npy', tr_new)

In [22]:
tr_new[1190]

array([[ 8.70896079e-01, -1.64876456e-02, -4.91190571e-01,
         3.45015360e+01],
       [ 1.46275003e-01, -9.45448436e-01,  2.91085688e-01,
        -1.13773225e+01],
       [-4.69194675e-01, -3.25354287e-01, -8.20975606e-01,
         2.08923276e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [ ]:
import cv2.aruco as aruco

img = cv2.imread('/home/andrey/ObjectDatasetTools/LINEMOD/test_close/JPEGImages/5.jpg')

gray_src = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
aruco_dict = aruco.getPredefinedDictionary(aruco.DICT_4X4_250)
parameters =  aruco.DetectorParameters()
detector = aruco.ArucoDetector(aruco_dict, parameters)

print(detector.detectMarkers(gray_src))
cv2.imshow('j', img)
cv2.waitKey()
cv2.destroyAllWindows()

((), None, (array([[[307., 330.],
        [320., 334.],
        [315., 345.],
        [303., 340.]]], dtype=float32), array([[[160., 300.],
        [172., 304.],
        [164., 318.],
        [150., 314.]]], dtype=float32), array([[[108., 286.],
        [122., 290.],
        [112., 303.],
        [ 99., 299.]]], dtype=float32), array([[[353., 282.],
        [368., 286.],
        [357., 327.],
        [341., 321.]]], dtype=float32), array([[[275., 252.],
        [385., 278.],
        [358., 394.],
        [228., 354.]]], dtype=float32), array([[[142., 242.],
        [110., 286.],
        [ 96., 283.],
        [130., 238.]]], dtype=float32), array([[[133., 218.],
        [224., 239.],
        [169., 335.],
        [ 66., 303.]]], dtype=float32), array([[[307., 207.],
        [332., 211.],
        [330., 223.],
        [304., 218.]]], dtype=float32), array([[[348.,  94.],
        [424., 104.],
        [413., 154.],
        [328., 139.]]], dtype=float32), array([[[291., 280.],
        [319

QObject::moveToThread: Current thread (0x21d3150) is not the object's thread (0x27e4570).
Cannot move to target thread (0x21d3150)

QObject::moveToThread: Current thread (0x21d3150) is not the object's thread (0x27e4570).
Cannot move to target thread (0x21d3150)

QObject::moveToThread: Current thread (0x21d3150) is not the object's thread (0x27e4570).
Cannot move to target thread (0x21d3150)

QObject::moveToThread: Current thread (0x21d3150) is not the object's thread (0x27e4570).
Cannot move to target thread (0x21d3150)

QObject::moveToThread: Current thread (0x21d3150) is not the object's thread (0x27e4570).
Cannot move to target thread (0x21d3150)

QObject::moveToThread: Current thread (0x21d3150) is not the object's thread (0x27e4570).
Cannot move to target thread (0x21d3150)

QObject::moveToThread: Current thread (0x21d3150) is not the object's thread (0x27e4570).
Cannot move to target thread (0x21d3150)

QObject::moveToThread: Current thread (0x21d3150) is not the object's thread

In [6]:
tr_new[50]

array([[ 0.50555598, -0.19680852,  0.84004735, -0.72122573],
       [-0.08065228, -0.98015299, -0.18109481,  0.03541971],
       [ 0.85901592,  0.02380183, -0.51139527, -0.3550988 ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [23]:
pip install dt-apriltags

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.7 MB/s eta 0:00:00m eta 0:00:010:00:01
Note: you may need to restart the kernel to use updated packages.


In [33]:
tvecs = np.load('/home/andrey/ObjectDatasetTools/tvecs.npy')
rvecs = np.load('/home/andrey/ObjectDatasetTools/rvecs.npy')

In [38]:
from scipy.spatial.transform import Rotation as R

rot_mtxs = R.from_rotvec(rvecs.reshape(-1,3)).as_matrix()

In [46]:
R.from_rotvec(rvecs[1].flatten()).as_matrix()


array([[ 0.96409988,  0.26550239, -0.00446172],
       [ 0.24318292, -0.8895517 , -0.38672967],
       [-0.10664659,  0.37176101, -0.92218233]])

In [45]:
rot_mtxs[1]

array([[ 0.96409988,  0.26550239, -0.00446172],
       [ 0.24318292, -0.8895517 , -0.38672967],
       [-0.10664659,  0.37176101, -0.92218233]])

In [54]:
transforms = np.array([np.vstack([np.hstack([np.array(rot_mtxs[idx]), np.array(tvecs[idx][0]).T]),np.array([0,0,0,1])]) for idx in range(1191)])

In [55]:
transforms[1:,1:3,:] *= -1

In [50]:
idx = 0
np.vstack([np.hstack([np.array(rot_mtxs[idx]), np.array(tvecs[idx][0]).T]),np.array([0,0,0,1])])

array([[ 0.96469711,  0.26316243,  0.01024822, -0.19572743],
       [ 0.24624952, -0.88753311, -0.38941771, -0.0357335 ],
       [-0.09338448,  0.37819376, -0.92100424,  0.25767825],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [56]:
np.save('/home/andrey/nvdiffrec/data/test_close/transforms_inverse.npy', transforms)